/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import Controle.ConectaBanco;
import Controle.ControleBairro;
import Modelo.ModeloBairro;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Cogeti
 */
public class FrmBairro extends javax.swing.JFrame {

    ConectaBanco connCidade = new ConectaBanco();
    ConectaBanco connEstado = new ConectaBanco();
    ConectaBanco connBairro = new ConectaBanco();
    ModeloBairro mod = new ModeloBairro();
    ControleBairro control = new ControleBairro();

    /**
     * Creates new form FRM
     */
    public FrmBairro() {
        initComponents();
        connEstado.conexao();
        connCidade.conexao();
        connBairro.conexao();
        jComboBoxSigla.removeAllItems();
        jComboBoxCidade.removeAllItems();
        connEstado.executaSQL("select * from estados order by sigla_estado");
        try {
            connEstado.rs.first();
            do {
                jComboBoxSigla.addItem(connEstado.rs.getString("sigla_estado"));
            } while (connEstado.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro do combobox sigla:/n" + ex);
        }
        connEstado.executaSQL("select * from estados where sigla_estado = '" + jComboBoxSigla.getSelectedItem() + "'");
        try {
            connEstado.rs.first();
            jComboBoxCidade = control.preencheCidades(jComboBoxCidade, (String) jComboBoxSigla.getSelectedItem());
        } catch (SQLException ex) {
            Logger.getLogger(FrmBairro.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1 = control.preencherTabela(jTable1);
        inicial();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jComboBoxCidade = new javax.swing.JComboBox<>();
        jComboBoxSigla = new javax.swing.JComboBox<>();
        jButtonAdd = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jButtonFirst = new javax.swing.JButton();
        jButtonLast = new javax.swing.JButton();
        jButtonPrevi = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Cadastro de Bairro");

        jLabel7.setText("Código:");

        jLabel8.setText("Nome:");

        jLabel9.setText("Cidade:");

        jLabel10.setText("Estado:");

        jTextFieldCod.setEnabled(false);

        jTextFieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroActionPerformed(evt);
            }
        });

        jComboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCidade.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxCidadePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBoxCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCidadeActionPerformed(evt);
            }
        });

        jComboBoxSigla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSigla.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxSiglaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBoxSigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSiglaActionPerformed(evt);
            }
        });

        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add-32.png"))); // NOI18N
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save_32.png"))); // NOI18N
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Edit-32.png"))); // NOI18N
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Delete-File-32.png"))); // NOI18N
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jButtonFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2leftarrow-32.png"))); // NOI18N
        jButtonFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstActionPerformed(evt);
            }
        });

        jButtonLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2rightarrow-32.png"))); // NOI18N
        jButtonLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLastActionPerformed(evt);
            }
        });

        jButtonPrevi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1leftarrow-32.png"))); // NOI18N
        jButtonPrevi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviActionPerformed(evt);
            }
        });

        jButtonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1rightarrow-32.png"))); // NOI18N
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Door-Out-32.png"))); // NOI18N
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonLast, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonPrevi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExit)
                    .addComponent(jButtonNext)
                    .addComponent(jButtonPrevi)
                    .addComponent(jButtonLast)
                    .addComponent(jButtonFirst)
                    .addComponent(jButtonDel)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonAdd))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroActionPerformed

    private void jComboBoxSiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSiglaActionPerformed

    }//GEN-LAST:event_jComboBoxSiglaActionPerformed

    private void jComboBoxCidadePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxCidadePopupMenuWillBecomeInvisible

    }//GEN-LAST:event_jComboBoxCidadePopupMenuWillBecomeInvisible

    private void jComboBoxSiglaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxSiglaPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        jComboBoxCidade = control.preencheCidades(jComboBoxCidade, (String) jComboBoxSigla.getSelectedItem());
    }//GEN-LAST:event_jComboBoxSiglaPopupMenuWillBecomeInvisible

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        try {
            mod.setNome_bairro(jTextFieldBairro.getText());
            connCidade.executaSQL("select * from cidade where nome_cidade = '" + jComboBoxCidade.getSelectedItem() + "'");
            connCidade.rs.first();
            mod.setId_cidade(connCidade.rs.getInt("id_cidade"));
            control.addBairro(mod);
            jTable1 = control.preencherTabela(jTable1);
            inicial();
        } catch (SQLException ex) {
            Logger.getLogger(FrmBairro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jComboBoxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCidadeActionPerformed

    private void jButtonFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstActionPerformed
        try {
            connBairro.executaSQL("select * from bairro order by id_bairro");
            connBairro.rs.first();
            jTextFieldCod.setText(String.valueOf(connBairro.rs.getInt("id_bairro")));
            jTextFieldBairro.setText(connBairro.rs.getString("nome_bairro"));
            connCidade.executaSQL("select * from cidade inner join estados on cidade.id_estado = estados.id_estado and id_cidade =" + connBairro.rs.getInt("id_cidade"));
            connCidade.rs.first();
            jComboBoxSigla.setSelectedItem(connCidade.rs.getString("sigla_estado"));
            jComboBoxCidade = control.preencheCidades(jComboBoxCidade, (String) jComboBoxSigla.getSelectedItem());
            jComboBoxCidade.setSelectedItem(connCidade.rs.getString("nome_cidade"));
            view_mode();
        } catch (SQLException ex) {
            Logger.getLogger(ControleBairro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonFirstActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        control.deleteBairro(Integer.parseInt(jTextFieldCod.getText()));
        jTable1 = control.preencherTabela(jTable1);
        inicial();
    }//GEN-LAST:event_jButtonDelActionPerformed

    private void jButtonLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLastActionPerformed
        try {
            connBairro.executaSQL("select * from bairro order by id_bairro");
            connBairro.rs.last();
            jTextFieldCod.setText(String.valueOf(connBairro.rs.getInt("id_bairro")));
            jTextFieldBairro.setText(connBairro.rs.getString("nome_bairro"));
            connCidade.executaSQL("select * from cidade inner join estados on cidade.id_estado = estados.id_estado and id_cidade =" + connBairro.rs.getInt("id_cidade"));
            connCidade.rs.first();
            jComboBoxSigla.setSelectedItem(connCidade.rs.getString("sigla_estado"));
            jComboBoxCidade = control.preencheCidades(jComboBoxCidade, (String) jComboBoxSigla.getSelectedItem());
            jComboBoxCidade.setSelectedItem(connCidade.rs.getString("nome_cidade"));
            view_mode();
        } catch (SQLException ex) {
            Logger.getLogger(ControleBairro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLastActionPerformed

    private void jButtonPreviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviActionPerformed
        try {
            connBairro.rs.previous();
            jTextFieldCod.setText(String.valueOf(connBairro.rs.getInt("id_bairro")));
            jTextFieldBairro.setText(connBairro.rs.getString("nome_bairro"));
            connCidade.executaSQL("select * from cidade inner join estados on cidade.id_estado = estados.id_estado and id_cidade =" + connBairro.rs.getInt("id_cidade"));
            connCidade.rs.first();
            jComboBoxSigla.setSelectedItem(connCidade.rs.getString("sigla_estado"));
            jComboBoxCidade = control.preencheCidades(jComboBoxCidade, (String) jComboBoxSigla.getSelectedItem());
            jComboBoxCidade.setSelectedItem(connCidade.rs.getString("nome_cidade"));
        } catch (SQLException ex) {
            Logger.getLogger(ControleBairro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPreviActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        try {
            connBairro.rs.next();
            jTextFieldCod.setText(String.valueOf(connBairro.rs.getInt("id_bairro")));
            jTextFieldBairro.setText(connBairro.rs.getString("nome_bairro"));
            connCidade.executaSQL("select * from cidade inner join estados on cidade.id_estado = estados.id_estado and id_cidade =" + connBairro.rs.getInt("id_cidade"));
            connCidade.rs.first();
            jComboBoxSigla.setSelectedItem(connCidade.rs.getString("sigla_estado"));
            jComboBoxCidade = control.preencheCidades(jComboBoxCidade, (String) jComboBoxSigla.getSelectedItem());
            jComboBoxCidade.setSelectedItem(connCidade.rs.getString("nome_cidade"));
        } catch (SQLException ex) {
            Logger.getLogger(ControleBairro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        try {
            connCidade.executaSQL("select * from cidade where nome_cidade = '"+jComboBoxCidade.getSelectedItem()+"'");
            connCidade.rs.first();
            mod.setId_cidade(connCidade.rs.getInt("id_cidade"));
            mod.setId_bairro(Integer.parseInt(jTextFieldCod.getText()));
            mod.setNome_bairro(jTextFieldBairro.getText()); 
            control.editaBairro(mod);
            inicial();
        } catch (SQLException ex) {
            Logger.getLogger(FrmBairro.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1 = control.preencherTabela(jTable1);
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        jButtonAdd.setEnabled(false);
        jButtonDel.setEnabled(false);
        jButtonEdit.setEnabled(false);
        jButtonSave.setEnabled(true);
        jButtonNext.setEnabled(false);
        jButtonPrevi.setEnabled(false);
        jButtonLast.setEnabled(false);
        jButtonFirst.setEnabled(false);
        jTextFieldBairro.setEnabled(true);
        jComboBoxCidade.setEnabled(true);
        jComboBoxSigla.setEnabled(true);
    }//GEN-LAST:event_jButtonEditActionPerformed
    
    public void clear(){
        jTextFieldCod.setText("");
        jTextFieldBairro.setText("");
        jComboBoxSigla.setSelectedItem("AC");
        jComboBoxCidade = control.preencheCidades(jComboBoxCidade, (String) jComboBoxSigla.getSelectedItem());       
    }
    
    public void inicial(){
        jButtonAdd.setEnabled(true);
        jButtonDel.setEnabled(false);
        jButtonEdit.setEnabled(false);
        jButtonSave.setEnabled(false);
        jButtonNext.setEnabled(false);
        jButtonPrevi.setEnabled(false);
        jButtonLast.setEnabled(true);
        jButtonFirst.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jComboBoxCidade.setEnabled(true);
        jComboBoxSigla.setEnabled(true);
        clear();
    }
    
    public void view_mode(){
        jButtonAdd.setEnabled(false);
        jButtonDel.setEnabled(true);
        jButtonEdit.setEnabled(true);
        jButtonSave.setEnabled(false);
        jButtonNext.setEnabled(true);
        jButtonPrevi.setEnabled(true);
        jTextFieldBairro.setEnabled(false);
        jComboBoxCidade.setEnabled(false);
        jComboBoxSigla.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBairro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonFirst;
    private javax.swing.JButton jButtonLast;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevi;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxCidade;
    private javax.swing.JComboBox<String> jComboBoxSigla;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCod;
    // End of variables declaration//GEN-END:variables
}
