/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import Controle.ConectaBanco;
import Controle.ControleCliente;
import Modelo.ModeloCliente;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Cogeti
 */
public class FrmClientes extends javax.swing.JFrame {

    ConectaBanco connCliente = new ConectaBanco();
    ConectaBanco connTel = new ConectaBanco();
    ConectaBanco connBairro = new ConectaBanco();
    ConectaBanco connCidade = new ConectaBanco();
    ModeloCliente mod = new ModeloCliente();
    ControleCliente control = new ControleCliente();

    /**
     * Creates new form FrmClientes
     */
    public FrmClientes() {
        connCidade.conexao();
        connBairro.conexao();
        connCliente.conexao();
        connTel.conexao();
        initComponents();
        initFormatedFields();
        try {
            jComboBoxEstado = control.preencheComboEstado(jComboBoxEstado);
            jComboBoxTel = control.preencheComboTel(jComboBoxTel);
        } catch (SQLException ex) {
            Logger.getLogger(FrmClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable = control.preencherTabela(jTable);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jComboBoxTel = new javax.swing.JComboBox<>();
        jButtonAddTel = new javax.swing.JButton();
        jFormattedTextFieldRG = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jComboBoxBairro = new javax.swing.JComboBox<>();
        jComboBoxCidade = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonAddBairro = new javax.swing.JButton();
        jButtonAddCidade = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonFirst = new javax.swing.JButton();
        jButtonLast = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Clientes");

        jLabel2.setText("Cod:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Endereço:");

        jLabel6.setText("CPF:");

        jLabel7.setText("R.G:");

        jLabel8.setText("Cidade:");

        jLabel9.setText("Bairro:");

        jTextFieldCod.setEnabled(false);

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jButtonAddTel.setText("+");
        jButtonAddTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTelActionPerformed(evt);
            }
        });

        jComboBoxBairro.setEnabled(false);

        jComboBoxCidade.setEnabled(false);
        jComboBoxCidade.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxCidadePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel10.setText("Estado:");

        jComboBoxEstado.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxEstadoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jScrollPane1.setViewportView(jTable);

        jButtonAddBairro.setText("+");
        jButtonAddBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBairroActionPerformed(evt);
            }
        });

        jButtonAddCidade.setText("+");
        jButtonAddCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCidadeActionPerformed(evt);
            }
        });

        jButtonNew.setText("Novo");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jButtonSave.setText("Salvar");
        jButtonSave.setEnabled(false);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Editar");
        jButtonEdit.setEnabled(false);
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Excluir");
        jButtonDelete.setEnabled(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonFirst.setText("<<");
        jButtonFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstActionPerformed(evt);
            }
        });

        jButtonLast.setText(">>");
        jButtonLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLastActionPerformed(evt);
            }
        });

        jButtonPrevious.setText("<");
        jButtonPrevious.setEnabled(false);
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });

        jButtonNext.setText(">");
        jButtonNext.setEnabled(false);
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonExit.setText("Sair");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete)
                        .addGap(61, 61, 61)
                        .addComponent(jButtonFirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLast)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxTel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddTel))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldRG))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddTel)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddBairro)
                    .addComponent(jButtonAddCidade))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNew)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonFirst)
                    .addComponent(jButtonLast)
                    .addComponent(jButtonPrevious)
                    .addComponent(jButtonNext)
                    .addComponent(jButtonExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 200, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initFormatedFields() {
        try {
            MaskFormatter form1 = new MaskFormatter("###.###.###-##");
            MaskFormatter form2 = new MaskFormatter("##.###.###-#");
            jFormattedTextFieldCPF.setFormatterFactory(new DefaultFormatterFactory(form1));
            jFormattedTextFieldRG.setFormatterFactory(new DefaultFormatterFactory(form2));
        } catch (ParseException ex) {
            Logger.getLogger(FrmTelefone.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonAddBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBairroActionPerformed
        FrmBairro frm = new FrmBairro();
        frm.setVisible(true);
    }//GEN-LAST:event_jButtonAddBairroActionPerformed

    private void jButtonAddTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTelActionPerformed
        FrmTelefone frm = new FrmTelefone();
        frm.setVisible(true);
        try {
            jComboBoxTel = control.preencheComboTel(jComboBoxTel);
        } catch (SQLException ex) {
            Logger.getLogger(FrmClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddTelActionPerformed

    private void jButtonAddCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCidadeActionPerformed
        FrmCidades frm = new FrmCidades();
        frm.setVisible(true);
    }//GEN-LAST:event_jButtonAddCidadeActionPerformed

    private void jComboBoxEstadoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxEstadoPopupMenuWillBecomeInvisible

        if ((String) jComboBoxEstado.getSelectedItem() == "") {
            jComboBoxCidade.setEnabled(false);
        } else {
            try {
                jComboBoxCidade = control.preencheComboCidade(jComboBoxCidade, (String) jComboBoxEstado.getSelectedItem());
            } catch (SQLException ex) {
                Logger.getLogger(FrmClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jComboBoxEstadoPopupMenuWillBecomeInvisible

    private void jComboBoxCidadePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxCidadePopupMenuWillBecomeInvisible
        if ((String) jComboBoxCidade.getSelectedItem() == "") {
            jComboBoxBairro.setEnabled(false);
        } else {
            try {
                jComboBoxBairro = control.preencheComboBairro(jComboBoxBairro, (String) jComboBoxCidade.getSelectedItem());
            } catch (SQLException ex) {
                Logger.getLogger(FrmClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jComboBoxCidadePopupMenuWillBecomeInvisible

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed

        try {
            connBairro.executaSQL("select * from bairro where nome_bairro = '"
                    + jComboBoxBairro.getSelectedItem() + "'");
            connBairro.rs.first();
            mod.setBairro(connBairro.rs.getInt("id_bairro"));
            connTel.executaSQL("select * from telefone where numero_tel = '"
                    + jComboBoxTel.getSelectedItem() + "'");
            connTel.rs.first();
            mod.setTel(connTel.rs.getInt("id_telefone"));
            connCidade.executaSQL("select * from cidade where nome_cidade = '" + jComboBoxCidade.getSelectedItem() + "'");
            connCidade.rs.first();
            mod.setCidade(connCidade.rs.getInt("id_cidade"));
            mod.setNome(jTextFieldNome.getText());
            mod.setEndereco(jTextFieldEndereco.getText());
            mod.setCpf(jFormattedTextFieldCPF.getText());
            mod.setRg(jFormattedTextFieldRG.getText());
            control.novo(mod);
            clear();
            inicial();
            jTable = control.preencherTabela(jTable);
        } catch (SQLException ex) {
            Logger.getLogger(FrmClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstActionPerformed
        String sigla, cidade, bairro;
        connCliente.executaSQL("select * from clientes order by id_cliente");
        try {
            if (connCliente.rs.first()) {
                jTextFieldCod.setText(String.valueOf(connCliente.rs.getInt("id_cliente")));
                jTextFieldNome.setText(connCliente.rs.getString("nome_cliente"));
                jTextFieldEndereco.setText(connCliente.rs.getString("endereco"));
                jFormattedTextFieldCPF.setText(connCliente.rs.getString("cpf_cliente"));
                jFormattedTextFieldRG.setText(connCliente.rs.getString("rg_cliente"));
                connTel.executaSQL("select * from telefone where id_telefone = " + connCliente.rs.getInt("id_telefone"));
                connTel.rs.first();
                jComboBoxTel.setSelectedItem(connTel.rs.getString("numero_tel"));
                connBairro.executaSQL("select * from bairro inner join cidade on"
                        + " bairro.id_cidade = cidade.id_cidade "
                        + "inner join estados on cidade.id_estado = estados.id_estado and id_bairro = " + connCliente.rs.getInt("id_bairro"));
                connBairro.rs.first();
                sigla = connBairro.rs.getString("sigla_estado");
                cidade = connBairro.rs.getString("nome_cidade");
                bairro = connBairro.rs.getString("nome_bairro");
                jComboBoxEstado.setSelectedItem(sigla);
                jComboBoxCidade = control.preencheComboCidade(jComboBoxCidade, sigla);
                jComboBoxCidade.setSelectedItem(cidade);
                jComboBoxBairro = control.preencheComboBairro(jComboBoxBairro, cidade);
                jComboBoxBairro.setSelectedItem(bairro);
                selecao();
                jButtonPrevious.setEnabled(false);
                if (connCliente.rs.next()) {
                    connCliente.rs.previous();
                    jButtonNext.setEnabled(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Não existem clientes cadastrados");
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonFirstActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        mod.setCod(Integer.parseInt(jTextFieldCod.getText()));
        control.exclui(mod);
        inicial();
        clear();
        jTable = control.preencherTabela(jTable);
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLastActionPerformed
        String sigla, cidade, bairro;
        try {
            connCliente.executaSQL("select * from clientes order by id_cliente");
            if (connCliente.rs.last()) {
                jTextFieldCod.setText(String.valueOf(connCliente.rs.getInt("id_cliente")));
                jTextFieldNome.setText(connCliente.rs.getString("nome_cliente"));
                jTextFieldEndereco.setText(connCliente.rs.getString("endereco"));
                jFormattedTextFieldCPF.setText(connCliente.rs.getString("cpf_cliente"));
                jFormattedTextFieldRG.setText(connCliente.rs.getString("rg_cliente"));
                connTel.executaSQL("select * from telefone where id_telefone = " + connCliente.rs.getInt("id_telefone"));
                connTel.rs.first();
                jComboBoxTel.setSelectedItem(connTel.rs.getString("numero_tel"));
                connBairro.executaSQL("select * from bairro inner join cidade on"
                        + " bairro.id_cidade = cidade.id_cidade "
                        + "inner join estados on cidade.id_estado = estados.id_estado and id_bairro = " + connCliente.rs.getInt("id_bairro"));
                connBairro.rs.first();
                sigla = connBairro.rs.getString("sigla_estado");
                cidade = connBairro.rs.getString("nome_cidade");
                bairro = connBairro.rs.getString("nome_bairro");
                jComboBoxEstado.setSelectedItem(sigla);
                jComboBoxCidade = control.preencheComboCidade(jComboBoxCidade, sigla);
                jComboBoxCidade.setSelectedItem(cidade);
                jComboBoxBairro = control.preencheComboBairro(jComboBoxBairro, cidade);
                jComboBoxBairro.setSelectedItem(bairro);
                selecao();
                jButtonNext.setEnabled(false);
                if (connCliente.rs.previous()) {
                    connCliente.rs.next();
                    jButtonPrevious.setEnabled(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Não existem clientes cadastrados");
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLastActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        String sigla, cidade, bairro;
        try {
            if (connCliente.rs.previous()) {
                jTextFieldCod.setText(String.valueOf(connCliente.rs.getInt("id_cliente")));
                jTextFieldNome.setText(connCliente.rs.getString("nome_cliente"));
                jTextFieldEndereco.setText(connCliente.rs.getString("endereco"));
                jFormattedTextFieldCPF.setText(connCliente.rs.getString("cpf_cliente"));
                jFormattedTextFieldRG.setText(connCliente.rs.getString("rg_cliente"));
                connTel.executaSQL("select * from telefone where id_telefone = " + connCliente.rs.getInt("id_telefone"));
                connTel.rs.first();
                jComboBoxTel.setSelectedItem(connTel.rs.getString("numero_tel"));
                connBairro.executaSQL("select * from bairro inner join cidade on"
                        + " bairro.id_cidade = cidade.id_cidade "
                        + "inner join estados on cidade.id_estado = estados.id_estado and id_bairro = " + connCliente.rs.getInt("id_bairro"));
                connBairro.rs.first();
                sigla = connBairro.rs.getString("sigla_estado");
                cidade = connBairro.rs.getString("nome_cidade");
                bairro = connBairro.rs.getString("nome_bairro");
                jComboBoxEstado.setSelectedItem(sigla);
                jComboBoxCidade = control.preencheComboCidade(jComboBoxCidade, sigla);
                jComboBoxCidade.setSelectedItem(cidade);
                jComboBoxBairro = control.preencheComboBairro(jComboBoxBairro, cidade);
                jComboBoxBairro.setEnabled(false);
                jComboBoxCidade.setEnabled(false);
                jComboBoxBairro.setSelectedItem(bairro);
                jButtonNext.setEnabled(true);
            } else {
                jButtonPrevious.setEnabled(false);
            }

        } catch (SQLException ex) {
            Logger.getLogger(FrmClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        String sigla, cidade, bairro;
        try {
            if (connCliente.rs.next()) {
                jTextFieldCod.setText(String.valueOf(connCliente.rs.getInt("id_cliente")));
                jTextFieldNome.setText(connCliente.rs.getString("nome_cliente"));
                jTextFieldEndereco.setText(connCliente.rs.getString("endereco"));
                jFormattedTextFieldCPF.setText(connCliente.rs.getString("cpf_cliente"));
                jFormattedTextFieldRG.setText(connCliente.rs.getString("rg_cliente"));
                connTel.executaSQL("select * from telefone where id_telefone = " + connCliente.rs.getInt("id_telefone"));
                connTel.rs.first();
                jComboBoxTel.setSelectedItem(connTel.rs.getString("numero_tel"));
                connBairro.executaSQL("select * from bairro inner join cidade on"
                        + " bairro.id_cidade = cidade.id_cidade "
                        + "inner join estados on cidade.id_estado = estados.id_estado and id_bairro = " + connCliente.rs.getInt("id_bairro"));
                connBairro.rs.first();
                sigla = connBairro.rs.getString("sigla_estado");
                cidade = connBairro.rs.getString("nome_cidade");
                bairro = connBairro.rs.getString("nome_bairro");
                jComboBoxEstado.setSelectedItem(sigla);
                jComboBoxCidade = control.preencheComboCidade(jComboBoxCidade, sigla);
                jComboBoxCidade.setSelectedItem(cidade);
                jComboBoxBairro = control.preencheComboBairro(jComboBoxBairro, cidade);
                jComboBoxBairro.setSelectedItem(bairro);
                jComboBoxBairro.setEnabled(false);
                jComboBoxCidade.setEnabled(false);
                jButtonPrevious.setEnabled(true);
            } else {
                jButtonNext.setEnabled(false);
            }

        } catch (SQLException ex) {
            Logger.getLogger(FrmClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        try {
            connBairro.executaSQL("select * from bairro inner join cidade on bairro.id_cidade = cidade.id_cidade "
                    + "inner join estados on cidade.id_estado = estados.id_estado and nome_bairro = '" + jComboBoxBairro.getSelectedItem() + "'");
            connBairro.rs.first();
            connTel.executaSQL("select * from telefone where numero_tel = '" + jComboBoxTel.getSelectedItem() + "'");
            connTel.rs.first();
            mod.setCod(Integer.parseInt(jTextFieldCod.getText()));
            mod.setNome(jTextFieldNome.getText());
            mod.setEndereco(jTextFieldEndereco.getText());
            mod.setCpf(jFormattedTextFieldCPF.getText());
            mod.setRg(jFormattedTextFieldRG.getText());
            mod.setTel(connTel.rs.getInt("id_telefone"));
            mod.setBairro(connBairro.rs.getInt("id_bairro"));
            mod.setCidade(connBairro.rs.getInt("id_cidade"));
            control.edita(mod);
            jTable = control.preencherTabela(jTable);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha na alteração dos dados!" + ex);
        }
        inicial();
        clear();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        edicao();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void clear() {
        jTextFieldCod.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldCPF.setText("");
        jFormattedTextFieldRG.setText("");
        jComboBoxEstado.setSelectedIndex(0);
        jComboBoxTel.setSelectedIndex(0);
        jComboBoxCidade.removeAllItems();
        jComboBoxCidade.setEnabled(false);
        jComboBoxBairro.setEnabled(false);
        jComboBoxBairro.removeAllItems();
    }

    private void selecao() {
        jButtonEdit.setEnabled(true);
        jButtonDelete.setEnabled(true);
        jButtonNew.setEnabled(false);
        jTextFieldEndereco.setEnabled(false);
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldCPF.setEnabled(false);
        jFormattedTextFieldRG.setEnabled(false);
        jComboBoxTel.setEnabled(false);
        jComboBoxEstado.setEnabled(false);
        jComboBoxCidade.setEnabled(false);
        jComboBoxBairro.setEnabled(false);
    }

    private void edicao() {
        jButtonSave.setEnabled(true);
        jButtonEdit.setEnabled(false);
        jButtonFirst.setEnabled(false);
        jButtonLast.setEnabled(false);
        jButtonNext.setEnabled(false);
        jButtonPrevious.setEnabled(false);
        jTextFieldEndereco.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jFormattedTextFieldRG.setEnabled(true);
        jComboBoxTel.setEnabled(true);
        jComboBoxEstado.setEnabled(true);
        jComboBoxCidade.setEnabled(true);
        jComboBoxBairro.setEnabled(true);
    }

    private void inicial() {
        jButtonEdit.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jButtonSave.setEnabled(false);
        jButtonNew.setEnabled(true);
        jButtonNext.setEnabled(false);
        jButtonPrevious.setEnabled(false);
        jButtonFirst.setEnabled(true);
        jButtonLast.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmClientes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBairro;
    private javax.swing.JButton jButtonAddCidade;
    private javax.swing.JButton jButtonAddTel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonFirst;
    private javax.swing.JButton jButtonLast;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxBairro;
    private javax.swing.JComboBox<String> jComboBoxCidade;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxTel;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldRG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
